version: "3.4"

services:
  db:
    restart: always
    container_name: harmony_db
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  app-db-data: