name: Backend Deploy AWS

on:
  pull_request:
    types:
      - labeled
    branches:
      - develop
      - main
  workflow_call:
    secrets:
      EC2_SSH_KEY:
        required: true
      HOST_DNS:
        required: true
      USERNAME:
        required: true
      TARGET_DIR:
        required: true


jobs:
  deploy-aws:
    if: ${{ github.event.label.name == 'deploy' }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
        SCRIPT_BEFORE: |
          cd /home/ubuntu/app
          cp backend/.env .
        SCRIPT_AFTER: |
          cd /home/ubuntu/app
          cp .env backend/
          cd backend/
          python3.11 -m pipenv install --categories packages
          sudo systemctl restart backend.service
          systemctl status backend.service
        EXCLUDE: "/.git/, .gitignore, /.github/, /devcontainers/, /tests/, .env.test.example, commit.txt, dump_entero.json, example.env, info.yml, LICENSE, README.md"

