name: Deploy Swagger to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Env setup
        run: cp example.env .env

      - name: Generate OpenAPI JSON
        run: |
          pipenv run python -c "from fastapi.openapi.utils import get_openapi; from src.server import app; import json; open('openapi.json', 'w').write(json.dumps(get_openapi(title=app.title, version='3.0.0', openapi_version='3.0.0', description=app.description, routes=app.routes)))"

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: openapi.json

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./swagger-ui

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
